
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    image: php:fpm
    volumes:
      - ./src:/var/www/html
